/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.VenderDAO;
import controller.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author user
 */
public class janelaVender extends javax.swing.JFrame {

    private Controller control;
    private VenderDAO vao;
            
   public janelaVender(Controller control) {
        this.control = control;
        initComponents();
    }

   private void VenderBotao(){
     btVender.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    realizarVenda();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao realizar venda: " + ex.getMessage());
                }
            }
        });}
    

    private void realizarVenda() throws SQLException {
        String tipo = "";

        if (btBit.isSelected()) {
            tipo = "Bitcoin";
        } else if (btEthe.isSelected()) {
            tipo = "Ethereum";
        } else if (btRip.isSelected()) {
            tipo = "Ripple";
        }

        if (!tipo.isEmpty()) {
            
                double quantidade = Double.parseDouble(txtQnt.getText());
                vao.vender(tipo, quantidade);
                JOptionPane.showMessageDialog(null, "Venda realizada com sucesso!"
                , "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            txtConfiraValor.setText("Selecione uma moeda antes de calcular.");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloSacar = new javax.swing.JLabel();
        btSairSacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCotacao = new javax.swing.JTextArea();
        lbltituloCotacao = new javax.swing.JLabel();
        lblTituloEscolha = new javax.swing.JLabel();
        txtTituloQnt = new javax.swing.JLabel();
        txtQnt = new javax.swing.JTextField();
        btCalcular = new javax.swing.JButton();
        lblTituloValor = new javax.swing.JLabel();
        txtConfiraValor = new javax.swing.JTextField();
        btVender = new javax.swing.JButton();
        lblTitloSaldo = new javax.swing.JLabel();
        txtCampoSaldo = new javax.swing.JTextField();
        btBit = new javax.swing.JToggleButton();
        btEthe = new javax.swing.JToggleButton();
        btRip = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblTituloSacar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloSacar.setText("VENDER CRIPTOMOEDAS");

        btSairSacar.setBackground(new java.awt.Color(255, 102, 0));
        btSairSacar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSairSacar.setText("X");
        btSairSacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairSacarMouseClicked(evt);
            }
        });
        btSairSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairSacarActionPerformed(evt);
            }
        });

        txtAreaCotacao.setEditable(false);
        txtAreaCotacao.setColumns(20);
        txtAreaCotacao.setRows(5);
        jScrollPane1.setViewportView(txtAreaCotacao);

        lbltituloCotacao.setText("COTAÇÃO:");

        lblTituloEscolha.setText("ESCOLHA QUAL DESEJA VENDER:");

        txtTituloQnt.setText("INSIRA A QUANTIDADE (ex: 2)");

        btCalcular.setText("CALCULAR");
        btCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCalcularMouseClicked(evt);
            }
        });

        lblTituloValor.setText("CONFIRA O VALOR (R$):");

        txtConfiraValor.setEditable(false);

        btVender.setText("VENDER");
        btVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVenderMouseClicked(evt);
            }
        });

        lblTitloSaldo.setText("SALDO (REAIS):");

        txtCampoSaldo.setEditable(false);

        btBit.setText("Bitcoin");

        btEthe.setText("Ethereum");

        btRip.setText("Ripple");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitloSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCampoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltituloCotacao)
                    .addComponent(lblTituloEscolha)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTituloQnt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCalcular))
                            .addComponent(lblTituloValor)
                            .addComponent(txtConfiraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btVender, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTituloSacar)
                        .addGap(61, 61, 61)
                        .addComponent(btSairSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btBit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEthe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRip)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btSairSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTituloSacar)
                .addGap(18, 18, 18)
                .addComponent(lbltituloCotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloEscolha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBit)
                    .addComponent(btEthe)
                    .addComponent(btRip))
                .addGap(32, 32, 32)
                .addComponent(txtTituloQnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTituloValor)
                .addGap(4, 4, 4)
                .addComponent(txtConfiraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitloSaldo)
                    .addComponent(txtCampoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairSacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairSacarMouseClicked

    }//GEN-LAST:event_btSairSacarMouseClicked

    private void btSairSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairSacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSairSacarActionPerformed

    private void btCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCalcularMouseClicked
        
    }//GEN-LAST:event_btCalcularMouseClicked

    private void btVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVenderMouseClicked
       
    }//GEN-LAST:event_btVenderMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(janelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(janelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(janelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(janelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new janelaVender().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btBit;
    private javax.swing.JButton btCalcular;
    private javax.swing.JToggleButton btEthe;
    private javax.swing.JToggleButton btRip;
    private javax.swing.JButton btSairSacar;
    private javax.swing.JButton btVender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitloSaldo;
    private javax.swing.JLabel lblTituloEscolha;
    private javax.swing.JLabel lblTituloSacar;
    private javax.swing.JLabel lblTituloValor;
    private javax.swing.JLabel lbltituloCotacao;
    private javax.swing.JTextArea txtAreaCotacao;
    private javax.swing.JTextField txtCampoSaldo;
    private javax.swing.JTextField txtConfiraValor;
    private javax.swing.JTextField txtQnt;
    private javax.swing.JLabel txtTituloQnt;
    // End of variables declaration//GEN-END:variables
}